### ISSUE TITLE
Null Pointer Exception

### ISSUE THREAD

**Issue by khayyatzy** [qcri/Qnoise#4]
Hi,

I got the following error when trying the example in Qnoise:

[khayyzy@kw2260 Qnoise-master]$ ./qnoise.sh -f examples/Inconsist1.json -o /home/khayyzy/data
Exception : null
java.lang.NullPointerException
    at qa.qcri.qnoise.DataProfile.getColumnIndex(Unknown Source)
    at qa.qcri.qnoise.constraint.PredicateConstraint.isValid(Unknown Source)
    at qa.qcri.qnoise.inject.InconsistencyInjector.filter(Unknown Source)
    at qa.qcri.qnoise.inject.InconsistencyInjector.inject(Unknown Source)
    at qa.qcri.qnoise.Qnoise.main(Unknown Source)
[khayyzy@kw2260 Qnoise-master]$

**Comment by zyzyis** [comment]
Hi Zuhair,

I fixed it in the latest commit. Thanks for finding it!

Si

**Comment by khayyatzy** [comment]
Hi Si,

Thank you for fixing it. However I still have it on my own dataset!

# 

[khayyzy@kw2260 Qnoise-master]$ ./qnoise.sh -f tpch100k.json -o /home/khayyzy/data/dirty/tpch_100k
Exception : null
java.lang.NullPointerException
    at java.util.regex.Matcher.getTextLength(Matcher.java:1234)
    at java.util.regex.Matcher.reset(Matcher.java:308)
    at java.util.regex.Matcher.<init>(Matcher.java:228)
    at java.util.regex.Pattern.matcher(Pattern.java:1088)
    at qa.qcri.qnoise.constraint.PredicateConstraint.parse(Unknown Source)
    at qa.qcri.qnoise.constraint.ConstraintFactory.createConstraintFromString(Unknown Source)
    at qa.qcri.qnoise.inject.InconsistencyInjector.inject(Unknown Source)

#     at qa.qcri.qnoise.Qnoise.main(Unknown Source)

# Here is my json file:

{
    "source" : {
        "path" : "/home/khayyzy/data/joined/100k_tpch",
        "type" : ["NUMERICAL", "NUMERICAL", "NUMERICAL","TEXT","TEXT","NUMERICAL","TEXT","NUMERICAL","TEXT","TEXT","TEXT","NUMERICAL","TEXT"]
    },
    "noise" : {
        "noisetype" : "i",
        "granularity" : "cell",
        "percentage" : 0.1,
        "model" : "r",
        "distance" : 0.0
        "column" : "c_name"
    }
}

**Comment by ghost** [comment]
Hi Zuhair,

It looks like that you are using a inconsistency type without giving the predicate? Maybe you can check the example?

I will improve more on the error handling.

Si
On 01/16/2014 10:15 AM, Zuhair Khayyat wrote:

Hi Si,

Thank you for fixing it. However I still have it on my own dataset!

[khayyzy@kw2260 Qnoise-master]$ ./qnoise.sh -f tpch100k.json -o /home/khayyzy/data/dirty/tpch_100k
Exception : null
java.lang.NullPointerException
at java.util.regex.Matcher.getTextLength(Matcher.java:1234)
at java.util.regex.Matcher.reset(Matcher.java:308)
at java.util.regex.Matcher.(Matcher.java:228)
at java.util.regex.Pattern.matcher(Pattern.java:1088)
at qa.qcri.qnoise.constraint.PredicateConstraint.parse(Unknown Source)
at qa.qcri.qnoise.constraint.ConstraintFactory.createConstraintFromString(Unknown Source)
at qa.qcri.qnoise.inject.InconsistencyInjector.inject(Unknown Source)

at qa.qcri.qnoise.Qnoise.main(Unknown Source)
Here is my json file:

{
"source" : {
"path" : "/home/khayyzy/data/joined/100k_tpch",
"type" : ["NUMERICAL", "NUMERICAL", "NUMERICAL","TEXT","TEXT","NUMERICAL","TEXT","NUMERICAL","TEXT","TEXT","TEXT","NUMERICAL","TEXT"]
},
"noise" : {
"noisetype" : "i",
"granularity" : "cell",
"percentage" : 0.1,
"model" : "r",
"distance" : 0.0
"column" : "c_name"
}
}

**Comment by khayyatzy** [comment]
Hi,

I see, can't I use the in inconsistency type on Strings with random edits?

**Comment by ghost** [comment]
Hi Zuhair,

Yes, you can. In that case you are not injecting inconsistency noise, but only works with duplicate as you mentioned in another mail.

To support inconsistency string, what kind of predicate you are expecting to use? or only Random pick?

Si

On 01/16/2014 11:29 AM, Zuhair Khayyat wrote:

Hi,

I see, can't I use the in inconsistency type on Strings with random edits?

**Comment by khayyatzy** [comment]
Hi Si,

The inconsistency I have in mind receives the attribute(s) name to be changed from the user and picks random rows. So by providing percentage of 0.1, I would expect that 10% of attribute X cells are changed with some edit distance.

Thank you,
Zuhair Khayyat

**Comment by zyzyis** [comment]
Hi Zuhair,

We introduced a new type of noise called 'ErrorNoise' to fit your need. You can find the examples/Error1.json example in the latest revision.

Si.

**Comment by khayyatzy** [comment]
Hi Si,

Thank you, I will try it :)

Regards,
Zuhair Khayyat
